import logic

import os
from kivy.app import App
from kivy.uix.widget import Widget
from kivy.core.window import Window

#Window.fullscreen = 'auto'

class MyLayout(Widget):
    country_list = ['USA', 'INDIA', 'BRAZIL', 'FRANCE', 'RUSSIA', 'TURKEY', 'UK', 'ITALY', 'SPAIN', 'GERMANY', 'ARGENTINA', 'COLOMBIA', 'POLAND', 'IRAN', 'MEXICO', 'UKRAINE', 'PERU', 'INDONESIA', 'CZECHIA', 'SOUTH AFRICA', 'NETHERLANDS', 'CANADA', 'CHILE', 'ROMANIA', 'IRAQ', 'PHILIPPINES', 'BELGIUM', 'SWEDEN', 'ISRAEL', 'PORTUGAL', 'PAKISTAN', 'HUNGARY', 'BANGLADESH', 'JORDAN', 'SERBIA', 'SWITZERLAND', 'AUSTRIA', 'JAPAN', 'LEBANON', 'UAE', 'MOROCCO', 'SAUDI ARABIA', 'BULGARIA', 'MALAYSIA', 'SLOVAKIA', 'ECUADOR', 'PANAMA', 'BELARUS', 'GREECE', 'CROATIA', 'AZERBAIJAN', 'KAZAKHSTAN', 'GEORGIA', 'NEPAL', 'TUNISIA', 'BOLIVIA', 'PALESTINE', 'PARAGUAY', 'KUWAIT', 'DOMINICAN REPUBLIC', 'ETHIOPIA', 'MOLDOVA', 'DENMARK', 'IRELAND', 'LITHUANIA', 'COSTA RICA', 'SLOVENIA', 'EGYPT', 'GUATEMALA', 'ARMENIA', 'HONDURAS', 'QATAR', 'BOSNIA AND HERZEGOVINA', 'VENEZUELA', 'OMAN', 'URUGUAY', 'LIBYA', 'BAHRAIN', 'NIGERIA', 'KENYA', 'NORTH MACEDONIA', 'MYANMAR', 'ALBANIA', 'ALGERIA', 'ESTONIA', 'S. KOREA', 'LATVIA', 'NORWAY', 'CUBA', 'SRI LANKA', 'MONTENEGRO', 'KYRGYZSTAN', 'GHANA', 'ZAMBIA', 'UZBEKISTAN', 'FINLAND', 'MOZAMBIQUE', 'EL SALVADOR', 'LUXEMBOURG', 'CAMEROON', 'CYPRUS', 'SINGAPORE', 'THAILAND', 'AFGHANISTAN', 'NAMIBIA', 'IVORY COAST', 'BOTSWANA', 'JAMAICA', 'UGANDA', 'SENEGAL', 'ZIMBABWE', 'MADAGASCAR', 'MALAWI', 'SUDAN', 'MONGOLIA', 'MALTA', 'AUSTRALIA', 'DRC', 'MALDIVES', 'ANGOLA', 'RWANDA', 'CABO VERDE', 'GABON', 'SYRIA', 'GUINEA', 'MAYOTTE', 'RÉUNION', 'FRENCH GUIANA', 'FRENCH POLYNESIA', 'ESWATINI', 'MAURITANIA', 'SOMALIA', 'GUADELOUPE', 'MALI', 'TAJIKISTAN', 'BURKINA FASO', 'ANDORRA', 'HAITI', 'TOGO', 'GUYANA', 'BELIZE', 'CURAÇAO', 'HONG KONG', 'DJIBOUTI', 'PAPUA NEW GUINEA', 'LESOTHO', 'CONGO', 'MARTINIQUE', 'ARUBA', 'CAMBODIA', 'SOUTH SUDAN', 'BAHAMAS', 'SURINAME', 'TRINIDAD AND TOBAGO', 'BENIN', 'EQUATORIAL GUINEA', 'NICARAGUA', 'ICELAND', 'CAR', 'YEMEN', 'GAMBIA', 'SEYCHELLES', 'NIGER', 'SAN MARINO', 'CHAD', 'SAINT LUCIA', 'GIBRALTAR', 'CHANNEL ISLANDS', 'SIERRA LEONE', 'BURUNDI', 'COMOROS', 'BARBADOS', 'GUINEA-BISSAU', 'ERITREA', 'LIECHTENSTEIN', 'VIETNAM', 'NEW ZEALAND', 'MONACO', 'TURKS AND CAICOS', 'BERMUDA', 'SAO TOME AND PRINCIPE', 'SINT MAARTEN', 'LIBERIA', 'TIMOR-LESTE', 'ST. VINCENT GRENADINES', 'SAINT MARTIN', 'ISLE OF MAN', 'CARIBBEAN NETHERLANDS', 'ANTIGUA AND BARBUDA', 'MAURITIUS', 'TAIWAN', 'BHUTAN', 'ST. BARTH', 'FAEROE ISLANDS', 'CAYMAN ISLANDS', 'TANZANIA', 'WALLIS AND FUTUNA', 'LAOS', 'BRUNEI ', 'BRITISH VIRGIN ISLANDS', 'DOMINICA', 'GRENADA', 'NEW CALEDONIA', 'FIJI', 'ANGUILLA', 'FALKLAND ISLANDS', 'MACAO', 'SAINT KITTS AND NEVIS', 'GREENLAND', 'VATICAN CITY', 'SAINT PIERRE MIQUELON', 'MONTSERRAT', 'SOLOMON ISLANDS', 'WESTERN SAHARA', 'VANUATU', 'MARSHALL ISLANDS', 'SAMOA', 'SAINT HELENA', 'MICRONESIA', 'CHINA', 'CHINA', 'USA', 'INDIA', 'BRAZIL', 'FRANCE', 'RUSSIA', 'TURKEY', 'UK', 'ITALY', 'SPAIN', 'GERMANY', 'ARGENTINA', 'COLOMBIA', 'POLAND', 'IRAN', 'MEXICO', 'UKRAINE', 'PERU', 'INDONESIA', 'CZECHIA', 'SOUTH AFRICA', 'NETHERLANDS', 'CANADA', 'CHILE', 'ROMANIA', 'IRAQ', 'PHILIPPINES', 'BELGIUM', 'SWEDEN', 'ISRAEL', 'PORTUGAL', 'PAKISTAN', 'HUNGARY', 'BANGLADESH', 'JORDAN', 'SERBIA', 'SWITZERLAND', 'AUSTRIA', 'JAPAN', 'LEBANON', 'UAE', 'MOROCCO', 'SAUDI ARABIA', 'BULGARIA', 'MALAYSIA', 'SLOVAKIA', 'ECUADOR', 'PANAMA', 'BELARUS', 'GREECE', 'CROATIA', 'AZERBAIJAN', 'KAZAKHSTAN', 'GEORGIA', 'NEPAL', 'TUNISIA', 'BOLIVIA', 'PALESTINE', 'PARAGUAY', 'KUWAIT', 'DOMINICAN REPUBLIC', 'ETHIOPIA', 'MOLDOVA', 'DENMARK', 'IRELAND', 'LITHUANIA', 'COSTA RICA', 'SLOVENIA', 'EGYPT', 'GUATEMALA', 'ARMENIA', 'HONDURAS', 'QATAR', 'BOSNIA AND HERZEGOVINA', 'VENEZUELA', 'OMAN', 'URUGUAY', 'LIBYA', 'BAHRAIN', 'NIGERIA', 'KENYA', 'NORTH MACEDONIA', 'MYANMAR', 'ALBANIA', 'ALGERIA', 'ESTONIA', 'S. KOREA', 'LATVIA', 'NORWAY', 'CUBA', 'SRI LANKA', 'MONTENEGRO', 'KYRGYZSTAN', 'GHANA', 'ZAMBIA', 'UZBEKISTAN', 'FINLAND', 'MOZAMBIQUE', 'EL SALVADOR', 'LUXEMBOURG', 'CAMEROON', 'CYPRUS', 'SINGAPORE', 'AFGHANISTAN', 'THAILAND', 'NAMIBIA', 'IVORY COAST', 'BOTSWANA', 'JAMAICA', 'UGANDA', 'SENEGAL', 'ZIMBABWE', 'MADAGASCAR', 'MALAWI', 'SUDAN', 'MONGOLIA', 'MALTA', 'AUSTRALIA', 'DRC', 'MALDIVES', 'ANGOLA', 'RWANDA', 'CABO VERDE', 'GABON', 'SYRIA', 'GUINEA', 'MAYOTTE', 'RÉUNION', 'FRENCH GUIANA', 'FRENCH POLYNESIA', 'ESWATINI', 'MAURITANIA', 'SOMALIA', 'GUADELOUPE', 'MALI', 'TAJIKISTAN', 'BURKINA FASO', 'ANDORRA', 'HAITI', 'TOGO', 'GUYANA', 'BELIZE', 'CURAÇAO', 'HONG KONG', 'DJIBOUTI', 'PAPUA NEW GUINEA', 'LESOTHO', 'CONGO', 'MARTINIQUE', 'ARUBA', 'CAMBODIA', 'SOUTH SUDAN', 'BAHAMAS', 'SURINAME', 'TRINIDAD AND TOBAGO', 'BENIN', 'EQUATORIAL GUINEA', 'NICARAGUA', 'ICELAND', 'CAR', 'YEMEN', 'GAMBIA', 'SEYCHELLES', 'NIGER', 'SAN MARINO', 'CHAD', 'SAINT LUCIA', 'GIBRALTAR', 'CHANNEL ISLANDS', 'SIERRA LEONE', 'BURUNDI', 'COMOROS', 'BARBADOS', 'GUINEA-BISSAU', 'ERITREA', 'LIECHTENSTEIN', 'VIETNAM', 'NEW ZEALAND', 'MONACO', 'TURKS AND CAICOS', 'BERMUDA', 'SAO TOME AND PRINCIPE', 'SINT MAARTEN', 'LIBERIA', 'TIMOR-LESTE', 'ST. VINCENT GRENADINES', 'SAINT MARTIN', 'ISLE OF MAN', 'CARIBBEAN NETHERLANDS', 'ANTIGUA AND BARBUDA', 'MAURITIUS', 'TAIWAN', 'BHUTAN', 'ST. BARTH', 'FAEROE ISLANDS', 'CAYMAN ISLANDS', 'TANZANIA', 'WALLIS AND FUTUNA', 'LAOS', 'BRUNEI ', 'BRITISH VIRGIN ISLANDS', 'DOMINICA', 'GRENADA', 'NEW CALEDONIA', 'FIJI', 'ANGUILLA', 'FALKLAND ISLANDS', 'MACAO', 'SAINT KITTS AND NEVIS', 'GREENLAND', 'VATICAN CITY', 'SAINT PIERRE MIQUELON', 'MONTSERRAT', 'SOLOMON ISLANDS', 'WESTERN SAHARA', 'VANUATU', 'MARSHALL ISLANDS', 'SAMOA', 'SAINT HELENA', 'MICRONESIA', 'CHINA', 'USA', 'INDIA', 'BRAZIL', 'FRANCE', 'RUSSIA', 'TURKEY', 'UK', 'ITALY', 'SPAIN', 'GERMANY', 'ARGENTINA', 'COLOMBIA', 'POLAND', 'IRAN', 'MEXICO', 'UKRAINE', 'PERU', 'INDONESIA', 'CZECHIA', 'SOUTH AFRICA', 'NETHERLANDS', 'CANADA', 'CHILE', 'ROMANIA', 'IRAQ', 'PHILIPPINES', 'BELGIUM', 'SWEDEN', 'ISRAEL', 'PORTUGAL', 'PAKISTAN', 'HUNGARY', 'BANGLADESH', 'JORDAN', 'SERBIA', 'SWITZERLAND', 'AUSTRIA', 'JAPAN', 'LEBANON', 'UAE', 'MOROCCO', 'SAUDI ARABIA', 'BULGARIA', 'MALAYSIA', 'SLOVAKIA', 'ECUADOR', 'PANAMA', 'BELARUS', 'GREECE', 'CROATIA', 'AZERBAIJAN', 'KAZAKHSTAN', 'GEORGIA', 'TUNISIA', 'NEPAL', 'BOLIVIA', 'PALESTINE', 'PARAGUAY', 'KUWAIT', 'DOMINICAN REPUBLIC', 'ETHIOPIA', 'MOLDOVA', 'DENMARK', 'IRELAND', 'LITHUANIA', 'COSTA RICA', 'SLOVENIA', 'EGYPT', 'GUATEMALA', 'ARMENIA', 'HONDURAS', 'QATAR', 'BOSNIA AND HERZEGOVINA', 'VENEZUELA', 'OMAN', 'URUGUAY', 'LIBYA', 'BAHRAIN', 'NIGERIA', 'KENYA', 'NORTH MACEDONIA', 'MYANMAR', 'ALBANIA', 'ALGERIA', 'ESTONIA', 'S. KOREA', 'LATVIA', 'NORWAY', 'CUBA', 'SRI LANKA', 'MONTENEGRO', 'KYRGYZSTAN', 'GHANA', 'ZAMBIA', 'UZBEKISTAN', 'FINLAND', 'MOZAMBIQUE', 'EL SALVADOR', 'LUXEMBOURG', 'CAMEROON', 'CYPRUS', 'SINGAPORE', 'AFGHANISTAN', 'THAILAND', 'NAMIBIA', 'BOTSWANA', 'IVORY COAST', 'JAMAICA', 'UGANDA', 'SENEGAL', 'ZIMBABWE', 'MADAGASCAR', 'MALAWI', 'SUDAN', 'MONGOLIA', 'MALTA', 'AUSTRALIA', 'DRC', 'MALDIVES', 'ANGOLA', 'RWANDA', 'GABON', 'CABO VERDE', 'SYRIA', 'GUINEA', 'MAYOTTE', 'RÉUNION', 'FRENCH GUIANA', 'FRENCH POLYNESIA', 'ESWATINI', 'MAURITANIA', 'SOMALIA', 'GUADELOUPE', 'MALI', 'TAJIKISTAN', 'BURKINA FASO', 'ANDORRA', 'HAITI', 'TOGO', 'GUYANA', 'BELIZE', 'CURAÇAO', 'HONG KONG', 'DJIBOUTI', 'LESOTHO', 'CONGO', 'PAPUA NEW GUINEA', 'MARTINIQUE', 'ARUBA', 'SOUTH SUDAN', 'BAHAMAS', 'SURINAME', 'CAMBODIA', 'TRINIDAD AND TOBAGO', 'BENIN', 'EQUATORIAL GUINEA', 'NICARAGUA', 'ICELAND', 'CAR', 'YEMEN', 'GAMBIA', 'SEYCHELLES', 'NIGER', 'SAN MARINO', 'CHAD', 'SAINT LUCIA', 'GIBRALTAR', 'CHANNEL ISLANDS', 'SIERRA LEONE', 'BURUNDI', 'COMOROS', 'BARBADOS', 'GUINEA-BISSAU', 'ERITREA', 'LIECHTENSTEIN', 'VIETNAM', 'NEW ZEALAND', 'MONACO', 'TURKS AND CAICOS', 'BERMUDA', 'SAO TOME AND PRINCIPE', 'SINT MAARTEN', 'LIBERIA', 'TIMOR-LESTE', 'ST. VINCENT GRENADINES', 'SAINT MARTIN', 'ISLE OF MAN', 'CARIBBEAN NETHERLANDS', 'ANTIGUA AND BARBUDA', 'MAURITIUS', 'TAIWAN', 'BHUTAN', 'ST. BARTH', 'FAEROE ISLANDS', 'CAYMAN ISLANDS', 'TANZANIA', 'WALLIS AND FUTUNA', 'LAOS', 'BRUNEI ', 'BRITISH VIRGIN ISLANDS', 'DOMINICA', 'GRENADA', 'NEW CALEDONIA', 'FIJI', 'ANGUILLA', 'FALKLAND ISLANDS', 'MACAO', 'SAINT KITTS AND NEVIS', 'GREENLAND', 'VATICAN CITY', 'SAINT PIERRE MIQUELON', 'MONTSERRAT', 'SOLOMON ISLANDS', 'WESTERN SAHARA', 'VANUATU', 'MARSHALL ISLANDS', 'SAMOA', 'SAINT HELENA', 'MICRONESIA']
    saves = []

    def spinner_clicked(self, value):
        actual, total = logic.get_country_covid_cases(value.upper())
        self.ids.actual.text = actual
        self.ids.total.text = total

    def load_saves(self):
        with open("saves.txt", "r") as f:
            self.saves = f.read()

        self.saves = self.saves.split()
        self.ids.spinner_id.values = self.saves

    def save(self):
        can_add = True
        country = self.country.text.upper()

        for x in self.saves:
            if country == x.upper():
                can_add = False
                break

        if country in self.country_list and can_add:
            self.country.text = ""
            with open('saves.txt', 'a') as file:
                file.write(country.upper() + "\n")

    def clear(self):
        with open('saves.txt', 'w') as f:
            f.write('WORLD' + '\n')


class MyGui(App):
    def build(self):
        self.title = 'COVID-19 Cases'
        self.icon = 'icon.png'

        if not os.path.exists('saves.txt'):
            with open('saves.txt', 'w') as f:
                f.write('WORLD' + '\n')

        return MyLayout()


if __name__ == "__main__":
    MyGui().run()
